// Generated by scripts/generate_countries.py — DO NOT EDIT
include <AFG.scad>
include <AGO.scad>
include <ARE.scad>
include <ARG.scad>
include <AUS.scad>
include <AUT.scad>
include <AZE.scad>
include <BEL.scad>
include <BEN.scad>
include <BFA.scad>
include <BGD.scad>
include <BGR.scad>
include <BIH.scad>
include <BLR.scad>
include <BOL.scad>
include <BRA.scad>
include <BWA.scad>
include <CAF.scad>
include <CAN.scad>
include <CHE.scad>
include <CHL.scad>
include <CHN.scad>
include <CIV.scad>
include <CMR.scad>
include <COD.scad>
include <COG.scad>
include <COL.scad>
include <CUB.scad>
include <CZE.scad>
include <DEU.scad>
include <DNK.scad>
include <DZA.scad>
include <ECU.scad>
include <EGY.scad>
include <ERI.scad>
include <ESP.scad>
include <EST.scad>
include <ETH.scad>
include <FIN.scad>
include <FRA.scad>
include <GAB.scad>
include <GBR.scad>
include <GEO.scad>
include <GHA.scad>
include <GIN.scad>
include <GRC.scad>
include <GRL.scad>
include <GTM.scad>
include <GUY.scad>
include <HND.scad>
include <HRV.scad>
include <HUN.scad>
include <IDN.scad>
include <IND.scad>
include <IRL.scad>
include <IRN.scad>
include <IRQ.scad>
include <ISL.scad>
include <ITA.scad>
include <JOR.scad>
include <JPN.scad>
include <KAZ.scad>
include <KEN.scad>
include <KGZ.scad>
include <KHM.scad>
include <KOR.scad>
include <LAO.scad>
include <LBR.scad>
include <LBY.scad>
include <LKA.scad>
include <LTU.scad>
include <LVA.scad>
include <MAR.scad>
include <MDA.scad>
include <MDG.scad>
include <MEX.scad>
include <MLI.scad>
include <MMR.scad>
include <MNG.scad>
include <MOZ.scad>
include <MRT.scad>
include <MWI.scad>
include <MYS.scad>
include <NAM.scad>
include <NER.scad>
include <NGA.scad>
include <NIC.scad>
include <NLD.scad>
include <NOR.scad>
include <NPL.scad>
include <NZL.scad>
include <OMN.scad>
include <PAK.scad>
include <PAN.scad>
include <PER.scad>
include <PHL.scad>
include <PNG.scad>
include <POL.scad>
include <PRK.scad>
include <PRT.scad>
include <PRY.scad>
include <ROU.scad>
include <RUSW.scad>
include <RUSE.scad>
include <SAH.scad>
include <SAU.scad>
include <SDN.scad>
include <SDS.scad>
include <SEN.scad>
include <SLE.scad>
include <SOL.scad>
include <SOM.scad>
include <SRB.scad>
include <SUR.scad>
include <SVK.scad>
include <SWE.scad>
include <SYR.scad>
include <TCD.scad>
include <THA.scad>
include <TJK.scad>
include <TKM.scad>
include <TUN.scad>
include <TUR.scad>
include <TZA.scad>
include <UGA.scad>
include <UKR.scad>
include <URY.scad>
include <USA.scad>
include <UZB.scad>
include <VEN.scad>
include <VNM.scad>
include <YEM.scad>
include <ZAF.scad>
include <ZMB.scad>
include <ZWE.scad>

module country(iso, part = "all") {
    if (iso == "AFG") country_AFG(part);
    else if (iso == "AGO") country_AGO(part);
    else if (iso == "ARE") country_ARE(part);
    else if (iso == "ARG") country_ARG(part);
    else if (iso == "AUS") country_AUS(part);
    else if (iso == "AUT") country_AUT(part);
    else if (iso == "AZE") country_AZE(part);
    else if (iso == "BEL") country_BEL(part);
    else if (iso == "BEN") country_BEN(part);
    else if (iso == "BFA") country_BFA(part);
    else if (iso == "BGD") country_BGD(part);
    else if (iso == "BGR") country_BGR(part);
    else if (iso == "BIH") country_BIH(part);
    else if (iso == "BLR") country_BLR(part);
    else if (iso == "BOL") country_BOL(part);
    else if (iso == "BRA") country_BRA(part);
    else if (iso == "BWA") country_BWA(part);
    else if (iso == "CAF") country_CAF(part);
    else if (iso == "CAN") country_CAN(part);
    else if (iso == "CHE") country_CHE(part);
    else if (iso == "CHL") country_CHL(part);
    else if (iso == "CHN") country_CHN(part);
    else if (iso == "CIV") country_CIV(part);
    else if (iso == "CMR") country_CMR(part);
    else if (iso == "COD") country_COD(part);
    else if (iso == "COG") country_COG(part);
    else if (iso == "COL") country_COL(part);
    else if (iso == "CUB") country_CUB(part);
    else if (iso == "CZE") country_CZE(part);
    else if (iso == "DEU") country_DEU(part);
    else if (iso == "DNK") country_DNK(part);
    else if (iso == "DZA") country_DZA(part);
    else if (iso == "ECU") country_ECU(part);
    else if (iso == "EGY") country_EGY(part);
    else if (iso == "ERI") country_ERI(part);
    else if (iso == "ESP") country_ESP(part);
    else if (iso == "EST") country_EST(part);
    else if (iso == "ETH") country_ETH(part);
    else if (iso == "FIN") country_FIN(part);
    else if (iso == "FRA") country_FRA(part);
    else if (iso == "GAB") country_GAB(part);
    else if (iso == "GBR") country_GBR(part);
    else if (iso == "GEO") country_GEO(part);
    else if (iso == "GHA") country_GHA(part);
    else if (iso == "GIN") country_GIN(part);
    else if (iso == "GRC") country_GRC(part);
    else if (iso == "GRL") country_GRL(part);
    else if (iso == "GTM") country_GTM(part);
    else if (iso == "GUY") country_GUY(part);
    else if (iso == "HND") country_HND(part);
    else if (iso == "HRV") country_HRV(part);
    else if (iso == "HUN") country_HUN(part);
    else if (iso == "IDN") country_IDN(part);
    else if (iso == "IND") country_IND(part);
    else if (iso == "IRL") country_IRL(part);
    else if (iso == "IRN") country_IRN(part);
    else if (iso == "IRQ") country_IRQ(part);
    else if (iso == "ISL") country_ISL(part);
    else if (iso == "ITA") country_ITA(part);
    else if (iso == "JOR") country_JOR(part);
    else if (iso == "JPN") country_JPN(part);
    else if (iso == "KAZ") country_KAZ(part);
    else if (iso == "KEN") country_KEN(part);
    else if (iso == "KGZ") country_KGZ(part);
    else if (iso == "KHM") country_KHM(part);
    else if (iso == "KOR") country_KOR(part);
    else if (iso == "LAO") country_LAO(part);
    else if (iso == "LBR") country_LBR(part);
    else if (iso == "LBY") country_LBY(part);
    else if (iso == "LKA") country_LKA(part);
    else if (iso == "LTU") country_LTU(part);
    else if (iso == "LVA") country_LVA(part);
    else if (iso == "MAR") country_MAR(part);
    else if (iso == "MDA") country_MDA(part);
    else if (iso == "MDG") country_MDG(part);
    else if (iso == "MEX") country_MEX(part);
    else if (iso == "MLI") country_MLI(part);
    else if (iso == "MMR") country_MMR(part);
    else if (iso == "MNG") country_MNG(part);
    else if (iso == "MOZ") country_MOZ(part);
    else if (iso == "MRT") country_MRT(part);
    else if (iso == "MWI") country_MWI(part);
    else if (iso == "MYS") country_MYS(part);
    else if (iso == "NAM") country_NAM(part);
    else if (iso == "NER") country_NER(part);
    else if (iso == "NGA") country_NGA(part);
    else if (iso == "NIC") country_NIC(part);
    else if (iso == "NLD") country_NLD(part);
    else if (iso == "NOR") country_NOR(part);
    else if (iso == "NPL") country_NPL(part);
    else if (iso == "NZL") country_NZL(part);
    else if (iso == "OMN") country_OMN(part);
    else if (iso == "PAK") country_PAK(part);
    else if (iso == "PAN") country_PAN(part);
    else if (iso == "PER") country_PER(part);
    else if (iso == "PHL") country_PHL(part);
    else if (iso == "PNG") country_PNG(part);
    else if (iso == "POL") country_POL(part);
    else if (iso == "PRK") country_PRK(part);
    else if (iso == "PRT") country_PRT(part);
    else if (iso == "PRY") country_PRY(part);
    else if (iso == "ROU") country_ROU(part);
    else if (iso == "RUSW") country_RUSW(part);
    else if (iso == "RUSE") country_RUSE(part);
    else if (iso == "SAH") country_SAH(part);
    else if (iso == "SAU") country_SAU(part);
    else if (iso == "SDN") country_SDN(part);
    else if (iso == "SDS") country_SDS(part);
    else if (iso == "SEN") country_SEN(part);
    else if (iso == "SLE") country_SLE(part);
    else if (iso == "SOL") country_SOL(part);
    else if (iso == "SOM") country_SOM(part);
    else if (iso == "SRB") country_SRB(part);
    else if (iso == "SUR") country_SUR(part);
    else if (iso == "SVK") country_SVK(part);
    else if (iso == "SWE") country_SWE(part);
    else if (iso == "SYR") country_SYR(part);
    else if (iso == "TCD") country_TCD(part);
    else if (iso == "THA") country_THA(part);
    else if (iso == "TJK") country_TJK(part);
    else if (iso == "TKM") country_TKM(part);
    else if (iso == "TUN") country_TUN(part);
    else if (iso == "TUR") country_TUR(part);
    else if (iso == "TZA") country_TZA(part);
    else if (iso == "UGA") country_UGA(part);
    else if (iso == "UKR") country_UKR(part);
    else if (iso == "URY") country_URY(part);
    else if (iso == "USA") country_USA(part);
    else if (iso == "UZB") country_UZB(part);
    else if (iso == "VEN") country_VEN(part);
    else if (iso == "VNM") country_VNM(part);
    else if (iso == "YEM") country_YEM(part);
    else if (iso == "ZAF") country_ZAF(part);
    else if (iso == "ZMB") country_ZMB(part);
    else if (iso == "ZWE") country_ZWE(part);
    else echo(str("Unknown country code: ", iso));
}

module all_countries(part = "all") {
    country_AFG(part);
    country_AGO(part);
    country_ARE(part);
    country_ARG(part);
    country_AUS(part);
    country_AUT(part);
    country_AZE(part);
    country_BEL(part);
    country_BEN(part);
    country_BFA(part);
    country_BGD(part);
    country_BGR(part);
    country_BIH(part);
    country_BLR(part);
    country_BOL(part);
    country_BRA(part);
    country_BWA(part);
    country_CAF(part);
    country_CAN(part);
    country_CHE(part);
    country_CHL(part);
    country_CHN(part);
    country_CIV(part);
    country_CMR(part);
    country_COD(part);
    country_COG(part);
    country_COL(part);
    country_CUB(part);
    country_CZE(part);
    country_DEU(part);
    country_DNK(part);
    country_DZA(part);
    country_ECU(part);
    country_EGY(part);
    country_ERI(part);
    country_ESP(part);
    country_EST(part);
    country_ETH(part);
    country_FIN(part);
    country_FRA(part);
    country_GAB(part);
    country_GBR(part);
    country_GEO(part);
    country_GHA(part);
    country_GIN(part);
    country_GRC(part);
    country_GRL(part);
    country_GTM(part);
    country_GUY(part);
    country_HND(part);
    country_HRV(part);
    country_HUN(part);
    country_IDN(part);
    country_IND(part);
    country_IRL(part);
    country_IRN(part);
    country_IRQ(part);
    country_ISL(part);
    country_ITA(part);
    country_JOR(part);
    country_JPN(part);
    country_KAZ(part);
    country_KEN(part);
    country_KGZ(part);
    country_KHM(part);
    country_KOR(part);
    country_LAO(part);
    country_LBR(part);
    country_LBY(part);
    country_LKA(part);
    country_LTU(part);
    country_LVA(part);
    country_MAR(part);
    country_MDA(part);
    country_MDG(part);
    country_MEX(part);
    country_MLI(part);
    country_MMR(part);
    country_MNG(part);
    country_MOZ(part);
    country_MRT(part);
    country_MWI(part);
    country_MYS(part);
    country_NAM(part);
    country_NER(part);
    country_NGA(part);
    country_NIC(part);
    country_NLD(part);
    country_NOR(part);
    country_NPL(part);
    country_NZL(part);
    country_OMN(part);
    country_PAK(part);
    country_PAN(part);
    country_PER(part);
    country_PHL(part);
    country_PNG(part);
    country_POL(part);
    country_PRK(part);
    country_PRT(part);
    country_PRY(part);
    country_ROU(part);
    country_RUSW(part);
    country_RUSE(part);
    country_SAH(part);
    country_SAU(part);
    country_SDN(part);
    country_SDS(part);
    country_SEN(part);
    country_SLE(part);
    country_SOL(part);
    country_SOM(part);
    country_SRB(part);
    country_SUR(part);
    country_SVK(part);
    country_SWE(part);
    country_SYR(part);
    country_TCD(part);
    country_THA(part);
    country_TJK(part);
    country_TKM(part);
    country_TUN(part);
    country_TUR(part);
    country_TZA(part);
    country_UGA(part);
    country_UKR(part);
    country_URY(part);
    country_USA(part);
    country_UZB(part);
    country_VEN(part);
    country_VNM(part);
    country_YEM(part);
    country_ZAF(part);
    country_ZMB(part);
    country_ZWE(part);
}
